# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - netlify.toml

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# Site settings
url: "https://cmphysicaltherapy.com"
baseurl: ""
title: "Christine Meizoso Physical Therapy"
description: |-
  At Christine Meizoso Physical Therapy we create an individualized patient treatment plan focused on 
  proper alignment, pain relief, improved body mechanics and tissue mobility. Our philosophy is to uncover 
  the root problem and treat the cause rather than just the underlying symptoms, resulting in maximized physical 
  potential and a return to a pain-free active lifestyle.
permalink: pretty
logo: "/assets/images/CM_logo.png"

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: What we treat
    url: /what-we-treat/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
