# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - netlify.toml

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# Site settings
url: "https://cmphysicaltherapy.com"
baseurl: ""
title: "Christine Meizoso Physical Therapy"
description: |-
  Physical therapy practice in midtown Manhattan, focusing on proper alignment, 
  pain relief, proper body mechanics and tissue mobility.  
  We aim to uncover the root of any problems and treat the cause not just the underlying symptoms 
  in order to maximize your potential and return to a pain-free, active lifestyle.
permalink: pretty
logo: "/assets/images/CM_logo.png"

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: What we treat
    url: /what-we-treat/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"

# Collection settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
